export const NOTE_TEMPLATES: Record<'en'|'zh'|'es', Record<string, string>> = {
  en: {
    flight: "Flight [Number] from [Origin] to [Destination] on [Date] was cancelled. The airline offered a voucher, but I want a full refund to my original payment method.",
    hotel: "Checked into [Hotel Name] on [Date]. The room was unacceptable due to [Issue: Hygiene/Safety/Noise]. I complained to the front desk at [Time], but they did not resolve it.",
    medical: "I had to cancel my trip scheduled for [Date] due to a medical emergency. I have attached a doctor's certificate diagnosing me with [Condition].",
    other: "I purchased [Service/Item] on [Date] for [Amount]. It was not provided as described because [Reason]. I contacted support on [Date] but received no response."
  },
  zh: {
    flight: "我预定的[日期]从[出发地]飞往[目的地]的航班[航班号]被取消了。航空公司只提供了代金券，但我要求退回到原支付方式。",
    hotel: "我在[日期]入住[酒店名称]，房间卫生/安全状况极差，具体问题是[问题描述]。我向前台投诉了但未获解决。",
    medical: "由于[日期]突发急病，我无法出行。已附上医生开具的诊断证明，确诊为[病情]。",
    other: "我在[日期]支付[金额]购买了[服务/商品]。由于[原因]，服务未按约定提供。我在[日期]联系了客服但无回应。"
  },
  es: {
    flight: "El vuelo [Número] de [Origen] a [Destino] el [Fecha] fue cancelado. La aerolínea ofreció un bono, pero quiero un reembolso completo a mi método de pago original.",
    hotel: "Me registré en [Nombre Hotel] el [Fecha]. La habitación era inaceptable debido a [Problema]. Me quejé en recepción a las [Hora], pero no lo solucionaron.",
    medical: "Tuve que cancelar mi viaje programado para el [Fecha] debido a una emergencia médica. Adjunto certificado médico con el diagnóstico [Condición].",
    other: "Compré [Servicio] el [Fecha] por [Monto]. No se entregó como se describió porque [Razón]. Contacté al soporte el [Fecha] sin respuesta."
  }
};

export const TRANSLATIONS = {
  en: {
    title: "Refund Multi-Agents",
    subtitle: "Your personal AI legal team. We fight for your travel refunds so you don't have to.",
    startNew: "Start New Case",
    startZh: "🇨🇳 开启中文服务",
    history: "Your Case History",
    searchPlaceholder: "Search by merchant, date, or amount...",
    evidenceDashboard: "Evidence Dashboard",
    evidenceSubtitle: "Choose how you want to add evidence:",
    files: "Files & Links",
    voice: "Voice Record",
    notes: "Manual Notes",
    analyze: "Analyze All Evidence ➔",
    processing: "Processing...",
    processingSub: "Our agents are reviewing your evidence.",
    analysisComplete: "Analysis Complete",
    analysisSub: "Here is the summary of your case and our legal assessment. Please correct any missing details.",
    saveTemplate: "💾 Save as Template",
    merchant: "Merchant Name",
    emailPlaceholder: "support@example.com",
    merchantEmail: "Merchant Email",
    amount: "Amount",
    currency: "Currency",
    date: "Date",
    reference: "Reference / PNR",
    issue: "Issue Description",
    verifiedSources: "Verified Sources",
    expertOpinion: "Expert Opinion",
    update: "Update",
    probability: "Probability",
    likely: "Likely Refundable",
    challenging: "Challenging Case",
    keyArgument: "Key Argument",
    strategy: "Strategy",
    generate: "✓ Generate Appeal Letter",
    back: "← Go Back",
    drafting: "Drafting...",
    letterReady: "Letter Ready!",
    letterSub: "Your professional appeal is ready to send.",
    copy: "📋 Copy",
    download: "⬇️ Download",
    draftEmail: "✉️ Draft Email",
    new: "🔄 New",
    error: "Error",
    retry: "Retry",
    dismiss: "Dismiss",
    templateStart: "Start from Template",
    noItems: "No items yet",
    recording: "Recording in progress...",
    tapRecord: "Tap to Record",
    recordHint: "Explain your situation verbally. We'll transcribe it.",
    dragDrop: "Drag & Drop or Click",
    pasteLink: "Paste Link (https://...)",
    micAccess: "Microphone access denied. Please allow microphone permissions.",
    speechUnsupport: "Speech recognition not supported in this browser.",
    provideEvidence: "Please provide some evidence (Photo, PDF, Audio) or a detailed description.",
    agentError: "Our agents encountered a problem processing your request.",
    requiredFields: "Please ensure all fields marked with * (Merchant, Amount, Currency, Date, Issue) are filled correctly before proceeding.",
    copied: "Letter copied to clipboard!",
    noDataSave: "No data to save!",
    templateSaved: "Template saved!",
    confirmClear: "Are you sure you want to clear the chat history?",
    processingFiles: "Processing...",
    autoSaved: "Auto-saved",
    lastSaved: "Last saved:",
    collectedEvidence: "Collected Evidence",
    selectMode: "Select Mode",
    useTemplate: "Quick Templates",
    tplFlight: "✈️ Flight",
    tplHotel: "🏨 Hotel",
    tplMedical: "🏥 Medical",
    tplGeneral: "📝 General",
    actionCheckFiles: "📂 Check Files",
    actionEditData: "📝 Edit Data",
    analysisNeeded: "Analysis Needed",
    analysisNeededSub: "Review extracted data and run policy check.",
    runAnalysis: "Run Policy Analysis",
    share: "Share",
    shareFallback: "Sharing not supported. Copied to clipboard.",
    openGmail: "Open Gmail",
    openOutlook: "Open Outlook",
    openDefault: "Default Mail App",
    missingInfo: "Missing Info",
    settings: "Settings",
    appearance: "Appearance",
    language: "Language",
    fontSize: "Font Size",
    modeLight: "Light",
    modeDark: "Dark",
    modeContrast: "High Contrast"
  },
  zh: {
    title: "多智能体退款助手",
    subtitle: "您的专属AI法律团队。我们帮您争取旅行退款，让您无后顾之忧。",
    startNew: "开始新案件",
    startZh: "🇨🇳 开启中文服务",
    history: "历史记录",
    searchPlaceholder: "搜索商家、日期或金额...",
    evidenceDashboard: "证据面板",
    evidenceSubtitle: "选择添加证据的方式：",
    files: "文件与链接",
    voice: "语音录入",
    notes: "手动备注",
    analyze: "开始分析证据 ➔",
    processing: "处理中...",
    processingSub: "智能体正在审核您的证据。",
    analysisComplete: "分析完成",
    analysisSub: "以下是案件摘要和法律评估。请修正任何缺失的细节。",
    saveTemplate: "💾 保存为模板",
    merchant: "商家名称",
    emailPlaceholder: "support@example.com",
    merchantEmail: "商家邮箱",
    amount: "金额",
    currency: "货币",
    date: "日期",
    reference: "参考号 / PNR",
    issue: "问题描述",
    verifiedSources: "已验证来源",
    expertOpinion: "专家意见",
    update: "更新",
    probability: "成功概率",
    likely: "退款可能性大",
    challenging: "具有挑战性",
    keyArgument: "关键论点",
    strategy: "策略",
    generate: "✓ 生成申诉信",
    back: "← 返回",
    drafting: "撰写中...",
    letterReady: "申诉信已就绪！",
    letterSub: "您的专业申诉信已准备好发送。",
    copy: "📋 复制",
    download: "⬇️ 下载",
    draftEmail: "✉️ 起草邮件",
    new: "🔄 新案件",
    error: "错误",
    retry: "重试",
    dismiss: "忽略",
    templateStart: "从模板开始",
    noItems: "暂无项目",
    recording: "正在录音...",
    tapRecord: "点击录音",
    recordHint: "口述您的情况，我们将为您转录。",
    dragDrop: "拖放或点击",
    pasteLink: "粘贴链接 (https://...)",
    micAccess: "麦克风访问被拒绝。请允许麦克风权限。",
    speechUnsupport: "此浏览器不支持语音识别。",
    provideEvidence: "请提供一些证据（照片、PDF、音频）或详细描述。",
    agentError: "我们的智能体在处理您的请求时遇到问题。",
    requiredFields: "请确保所有标有 * 的字段（商家、金额、货币、日期、问题）已正确填写。",
    copied: "信件已复制到剪贴板！",
    noDataSave: "没有数据可保存！",
    templateSaved: "模板已保存！",
    confirmClear: "您确定要清除聊天记录吗？",
    processingFiles: "处理中...",
    autoSaved: "已自动保存",
    lastSaved: "上次保存：",
    collectedEvidence: "已收集证据",
    selectMode: "选择模式",
    useTemplate: "快速模版",
    tplFlight: "✈️ 航班取消",
    tplHotel: "🏨 酒店问题",
    tplMedical: "🏥 突发就医",
    tplGeneral: "📝 通用退款",
    actionCheckFiles: "📂 检查文件",
    actionEditData: "📝 编辑数据",
    analysisNeeded: "需要分析",
    analysisNeededSub: "请检查提取的数据并运行政策分析。",
    runAnalysis: "运行政策分析",
    share: "分享",
    shareFallback: "不支持分享。已复制到剪贴板。",
    openGmail: "打开 Gmail",
    openOutlook: "打开 Outlook",
    openDefault: "默认邮件应用",
    missingInfo: "信息缺失",
    settings: "设置",
    appearance: "外观",
    language: "语言",
    fontSize: "字体大小",
    modeLight: "浅色",
    modeDark: "深色",
    modeContrast: "高对比"
  },
  es: {
    title: "Reembolso Multi-Agentes",
    subtitle: "Su equipo legal personal de IA. Luchamos por sus reembolsos de viaje.",
    startNew: "Iniciar Nuevo Caso",
    startZh: "🇨🇳 开启中文服务",
    history: "Historial de Casos",
    searchPlaceholder: "Buscar por comerciante, fecha o monto...",
    evidenceDashboard: "Panel de Evidencia",
    evidenceSubtitle: "Elija cómo agregar evidencia:",
    files: "Archivos y Enlaces",
    voice: "Grabación de Voz",
    notes: "Notas Manuales",
    analyze: "Analizar Evidencia ➔",
    processing: "Procesando...",
    processingSub: "Nuestros agentes están revisando su evidencia.",
    analysisComplete: "Análisis Completo",
    analysisSub: "Aquí está el resumen y nuestra evaluación legal. Por favor corrija los detalles faltantes.",
    saveTemplate: "💾 Guardar como Plantilla",
    merchant: "Comerciante",
    emailPlaceholder: "soporte@ejemplo.com",
    merchantEmail: "Email del Comerciante",
    amount: "Monto",
    currency: "Moneda",
    date: "Fecha",
    reference: "Referencia / PNR",
    issue: "Descripción del Problema",
    verifiedSources: "Fuentes Verificadas",
    expertOpinion: "Opinión Experta",
    update: "Actualizar",
    probability: "Probabilidad",
    likely: "Reembolso Probable",
    challenging: "Caso Desafiante",
    keyArgument: "Argumento Clave",
    strategy: "Estrategia",
    generate: "✓ Generar Carta",
    back: "← Volver",
    drafting: "Redactando...",
    letterReady: "¡Carta Lista!",
    letterSub: "Su carta de apelación profesional está lista.",
    copy: "📋 Copiar",
    download: "⬇️ Descargar",
    draftEmail: "✉️ Redactar Email",
    new: "🔄 Nuevo",
    error: "Error",
    retry: "Reintentar",
    dismiss: "Descartar",
    templateStart: "Iniciar desde Plantilla",
    noItems: "Sin ítems",
    recording: "Grabando...",
    tapRecord: "Tocar para Grabar",
    recordHint: "Explique su situación verbalmente.",
    dragDrop: "Arrastrar o Clic",
    pasteLink: "Pegar Enlace (https://...)",
    micAccess: "Acceso al micrófono denegado.",
    speechUnsupport: "Reconocimiento de voz no soportado.",
    provideEvidence: "Por favor proporcione evidencia (Foto, PDF, Audio) o descripción.",
    agentError: "Nuestros agentes encontraron un problema.",
    requiredFields: "Por favor complete los campos obligatorios *.",
    copied: "¡Carta copiada al portapapeles!",
    noDataSave: "¡No hay datos para guardar!",
    templateSaved: "¡Plantilla guardada!",
    confirmClear: "¿Está seguro de borrar el historial?",
    processingFiles: "Procesando...",
    autoSaved: "Autoguardado",
    lastSaved: "Último guardado:",
    collectedEvidence: "Evidencia Recopilada",
    selectMode: "Seleccionar Modo",
    useTemplate: "Plantillas Rápidas",
    tplFlight: "✈️ Vuelo",
    tplHotel: "🏨 Hotel",
    tplMedical: "🏥 Médico",
    tplGeneral: "📝 General",
    actionCheckFiles: "📂 Archivos",
    actionEditData: "📝 Editar",
    analysisNeeded: "Análisis Necesario",
    analysisNeededSub: "Revise los datos y ejecute el análisis.",
    runAnalysis: "Analizar Política",
    share: "Compartir",
    shareFallback: "No se admite compartir. Copiado al portapapeles.",
    openGmail: "Abrir Gmail",
    openOutlook: "Abrir Outlook",
    openDefault: "Correo Predeterminado",
    missingInfo: "Falta Información",
    settings: "Ajustes",
    appearance: "Apariencia",
    language: "Idioma",
    fontSize: "Tamaño de Fuente",
    modeLight: "Claro",
    modeDark: "Oscuro",
    modeContrast: "Alto Contraste"
  }
};